[build]
  command = "hugo --themesDir ../ --gc --minify -b $URL"
  # publish = "public"

[build.environment]
  HUGO_VERSION = "0.74.3"
  HUGO_ENABLEGITINFO = "true"

[context.production.environment]
  HUGO_ENV = "production"

[context.deploy-preview]
  command = "hugo --themesDir ../ --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "hugo --themesDir ../ --gc --minify -b $DEPLOY_PRIME_URL"

[[headers]]
  for = "*.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json; charset=UTF-8"

[[headers]]
  for = "index.xml"
  [headers.values]
    Content-Type = "application/rss+xml"

[[redirects]]
  from = "https://router.akjo.tech/*"
  to = "https://124.40.247.227:1805/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://router.akjo.tech/*"
  to = "https://124.40.247.227:1805/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://cv.akjo.tech/*"
  to = "https://akjo.tech/files/akshay_joshi_cv.pdf/:splat"
  status = 200
  force = true

[[redirects]]
  from = "http://cv.akjo.tech/*"
  to = "http://akjo.tech/files/akshay_joshi_cv.pdf/:splat"
  status = 200
  force = true
  
[[redirects]]
  from = "https://code.akjo.tech/*"
  to = "https://github.com/akshayjoshii/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://code.akjo.tech/*"
  to = "http://github.com/akshayjoshii/:splat"
  status = 301
  force = true
  
[[redirects]]
  from = "https://thesis.akjo.tech/*"
  to = "https://github.com/akshayjoshii/thesis/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://thesis.akjo.tech/*"
  to = "https://github.com/akshayjoshii/thesis/:splat"
  status = 301
  force = true
  
[[redirects]]
  from = "https://status.akjo.tech/*"
  to = "https://github.com/users/akshayjoshii/projects/3/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://status.akjo.tech/*"
  to = "https://github.com/users/akshayjoshii/projects/3/:splat"
  status = 301
  force = true
